### ISSUE TITLE
Comment and UserProfile Features

### ISSUE THREAD

**Issue by songrenzhao** [JiejayLan/unifreefrontend#56]
Technical Background:
- In the last sprint, we have completed our POST feature. In the following sprint, our goal is to allow users to write comment on a post. Also we should create a drop down menus for users to see their schools.

Acceptance Criteria:
- Modify SignUp page to accept 1 more parameter called `university`, should communicate to our backend APIs to sign up the user appropriately
- Create a drop down menus for users to visualize their schools 
- Refactor Post page to accept user comment

**Comment by jinchen1036** [comment]
- I don't think the frontend have implement all the POST feature, such as update and delete post.
- We have a **UserProfile** table in database, which have both school and major, so we should include both `university` and `major` in SignUp page, in which major can be an optional field.
- Also for university, we should not just accept the user input, since users might have typo and different naming for the same school, which will make it harder for backend to categorize the post by university. I think backend could provide a list of school which user search for their school.(ex search by like from database)

**Comment by songrenzhao** [comment]
> * I don't think the frontend have implement all the POST feature, such as update and delete post.
> * We have a **UserProfile** table in database, which have both school and major, so we should include both `university` and `major` in SignUp page, in which major can be an optional field.
> * Also for university, we should not just accept the user input, since users might have typo and different naming for the same school, which will make it harder for backend to categorize the post by university. I think backend could provide a list of school which user search for their school.(ex search by like from database)

We can extract user's school email address, since it contains school name in their emails

**Comment by ethen001** [comment]
>     * I don't think the frontend have implement all the POST feature, such as update and delete post.
> 
>     * We have a **UserProfile** table in database, which have both school and major, so we should include both `university` and `major` in SignUp page, in which major can be an optional field.
> 
>     * Also for university, we should not just accept the user input, since users might have typo and different naming for the same school, which will make it harder for backend to categorize the post by university. I think backend could provide a list of school which user search for their school.(ex search by like from database)

I agree. However, I do think we should implement update/delete post in front-end. I think these are key features for the purpose of the app.
* we can add an edit and delete button in the `IndividualPost` only visible to the owner which we can identify with the `canEdit` variable set in the backend.

**Comment by jinchen1036** [comment]
Since we have two weeks until next presentation, I think for this week our priority for the should be finish the post features in the frontend (which have no dependency on the backend) and start implement the create and view comments feature in both frontend and backend.

If we extract the school email to determine their school, then we probably should not ask user to type in their university. Please see this [link](http://doors.stanford.edu/~sr/universities.html), we can use that to do the match in the backend.

**Comment by songrenzhao** [comment]
Done
